meta_product_name: "Kanaku"
meta_title: "Kanaku - Connecting travellers to their next adventure"
meta_description: "Kanaku is an app which allows users to find the best places to be in new cities around the world."
meta_image: "Kanaku.jpg" # should exist in `app/assets/images/`
twitter_account: "@twitter"   # required for Twitter Cards
